### ISSUE TITLE
needs updating from odhcpd/src/ndp.c

### ISSUE THREAD

**Issue by nihilus** [CasperVector/6brd#1]
Nice work! Really love it. But the NDP code is slightly outdated. Merging the latest fix is a no-brainer however.

**Comment by CasperVector** [comment]
You mean openwrt/odhcpd@91a28e45?  I guess I would likely not merge that change, because:
* I am still far from able to fully understand the codebase, and still in the process of *reducing* it. 
* The original problem seems to be a result of rare protocol violation, and can self-resolve.
  (Of course, I may have completely misunderstood the problem, so please feel free to correct me.)

**Comment by nihilus** [comment]
Exactly!

**Comment by CasperVector** [comment]
Closing this issue then...
